### ISSUE TITLE
Current chapter calculation / select is broken

### ISSUE THREAD

**Issue by pichfl** [GianniCarlo/Audiobook-Player#103]
Since the move to CoreData the chapter selection screen can show multiple chapters as selected.

**Comment by pichfl** [comment]
@GianniCarlo Actually, I think this has a different origin. This happens when playing a book for the first time after the transition to CoreData. It starts fresh from the start while the previous position is still used to calculate the current chapter. 

It seems that while the data is imported correctly, the import is not used when playing the book

**Comment by GianniCarlo** [comment]
🤔 interesting. I figured some things might get broken after the migration to CoreData. I'll look into this too this week

**Comment by pichfl** [comment]
I think a colleague of mine gave me a hint to solving this: Reused table cells need a proper reset which doesn't happen here.
