### ISSUE TITLE
Books sometimes start erroneously from the beginning

### ISSUE THREAD

**Issue by pichfl** [GianniCarlo/Audiobook-Player#104]
It may be an development only issue but since we moved to CoreData books sometimes start from the beginning instead of the last saved position. Needs investigation.

**Comment by GianniCarlo** [comment]
The other day I jumped back from the lock screen and it took me to the end (or was it the beginning? 🤔) it definitely needs investigation

**Comment by pichfl** [comment]
I wonder if it is related to #106

**Comment by GianniCarlo** [comment]
looks related to #108

**Comment by pichfl** [comment]
I wasn't able to reproduce this for a while now, maybe it got fixed along the way?

**Comment by pichfl** [comment]
Nope, was able to reproduce today. Started an audiobook using the play action on the playlist (which looks for the first unfinished book) and it started the first book in a list of three from start instead of from about the middle. 

There must be an error in how we save, retrieve or calculate the last played position. No idea why
