### ISSUE TITLE
Trying to play a previously completed book crashes the app

### ISSUE THREAD

**Issue by pichfl** [GianniCarlo/Audiobook-Player#108]
I have yet to investigate this, but I suspect it might happen as opening a book will try to play from the last saved position which in turn would force a playback position beyond the duration of the file.

We should present but not play a book that was marked as finished.

**Comment by GianniCarlo** [comment]
This goes beyond having the book marked as finished. I was able to reproduce it jumping continuously between two files. Eventually one of the books will continue from the `currentTime` of the other,

**Comment by pichfl** [comment]
Fix in #113
