### ISSUE TITLE
Added Metadata author and title to file, but still..

### ISSUE THREAD

**Issue by hamning** [GianniCarlo/Audiobook-Player#11]
Getting caught by the following: 

      if title == "defaulttitle" && author == "defaultauthor" {
        self.showAlert(nil, message: "We can't correctly store your progress of books that don't have a title or author specified", style: .alert)
      }

What are the metadata fields it is looking for? I haven't been able to find it in the code yet. I added "Author" and "Title", but it is still tripping the error. 

Thanks

**Comment by GianniCarlo** [comment]
hi @hamning , the metadata that I look for are: title, author and artwork (`AVMetadataCommonKeyTitle`, `AVMetadataCommonKeyArtist`, `AVMetadataCommonKeyArtwork` respectively).

I recently patched this, so I might have not considered a specific scenario, can you share the audiobook with which you have the crashes? it will be a huge help to debug this crashes. If you can, email me to either gianni@criptext.com or gcarlo89@hotmail.com

Thanks for the headsup!

**Comment by hamning** [comment]
Very cool. I'll send it your way asap. Thanks for the quick reply. I'll shrink the file down first to make it easier to send and test.

**Comment by hamning** [comment]
Test files are on the way. Thank you very much sir.

**Comment by GianniCarlo** [comment]
@hamning I concluded my tests.

Short version, transform your `aac` to `mp3` and add the metadata to the new files (I do it with iTunes).

If you _must_ use `aac` files, then first we would need to:
- debug `AVPlayerItem` and see why it can't extract metadata from `aac` files
- If we can't solve the first one, then to use it without metadata we need to solve that the app can currently only hold one `unknown` clip (subsequent ones will override the previous one)

**Comment by GianniCarlo** [comment]
@hamning let me know if I can be of more help, I responded with an email with the test file converted to mp3 👍
