### ISSUE TITLE
Smart Rewind no longer applied

### ISSUE THREAD

**Issue by pichfl** [GianniCarlo/Audiobook-Player#116]
It seems the smart rewind feature got lost when the Book model got moved to CoreData.

`lastPlayed` is missing from CoreData models and no migration from the UserDefaults is present.

**Comment by GianniCarlo** [comment]
I'll look into this, this week

**Comment by pichfl** [comment]
If you look at this, I have a small change to this feature I would like to see: Instead of jumping back only after 10 minutes have passed, calculate the interval that should be jumped back in relation to the time that has passed, maxing out at 60 seconds after 10 minutes. That way pausing for 10 seconds should jump back a moment as well which will make the feature feel even more natural and helpful.

**Comment by GianniCarlo** [comment]
closed by #147
