### ISSUE TITLE
AirDrop support

### ISSUE THREAD

**Issue by vab9** [GianniCarlo/Audiobook-Player#13]
Hi! I really like the app. It is amazing for audiobooks. One feature I was missing though is the ability to add files through AirDrop, so I tried to implement this yesterday.

I would appreciate if you could take a look at my pull request #12 . As far as I can tell it seems to work. This is my first time contributing to an iOS app though, so you might want to triple check what I did there.

This issue is possibly a duplicate of #6 ...

**Comment by GianniCarlo** [comment]
Hi @vab9 , awesome work! I'll be testing it out throughout the day. I'll definitely include this in the new version of the app I'm planning for this weekend. 

The things that will be in the new version 1.3:
- AirDrop support (Thanks btw!)
- Remove the limitation of not being able to track correctly the progress of audiobooks without metadata (I'll be using SHA-1 as a better identifier of the file)
- Pass all the initial loading of the items to a background thread to stop freezing UI on app launch
- Edit the book name and author -> this is a solution for people that have books without metadata so they don't get lost in a sea of books titled "Unknown Book"
- (hopefully I finish this one) Create playlists -> this is a solution for people that have a book split in multiple mp3 files.

**Comment by GianniCarlo** [comment]
merged! didn't realize how much easier to upload books would be with airdrop support
