### ISSUE TITLE
Ideas / help

### ISSUE THREAD

**Issue by 0507spc** [GianniCarlo/Audiobook-Player#143]
Hi,

Firstly, I want to thank you for a great open source project! I use the app several time a week on my commute and while running at the weekend. It's much better than the other offerings, it is free and new ideas can be implemented by it's users! So again thank you for this.

A while ago I mentioned about being able to pause / play from headphones / bluetooth, and it was suggested I contribute to the project. In my lack of knowledge of swift, and time, someone else resolved that issue for me, to which I am very grateful!

I have some more ideas, and I have started to try to implement these myself. What is the best way to share these to the project (my GitHub / pull / branch / share skills are none existent). Also, my code, while it may work, may not fit the skill and style of yours, so I don't want to ruin / cause problems in your project.

**Comment by 0507spc** [comment]
So, i think i need to do a "pull request" and then just submit? Would I do this for all features or 1 pull feature?

**Comment by GianniCarlo** [comment]
I'm closing this issue, but feel free to continue the conversation

**Comment by 0507spc** [comment]
thanks. I'll try the above later.. there are a few simple things.. and then 2 bigger changes (a new player view and a new data source)

Swift and iOS programming is completely new as I mentioned, but I love this project and want to contribute. 

Some of the additions I can't test as I am not a paid developer, and can't compile to device due to app using containers.

so apologies if it doesn't work straight away.

**Comment by GianniCarlo** [comment]
I'm looking forward to your contributions @0507spc 👌 be sure to check the branch `next/major`, it has a redesign of the whole app, and it uses Core Data for the data source now

**Comment by pichfl** [comment]
Hey @0507spc we haven't heard from you in a while. Are you still interested in contributing? Feel free to send me an email (can be found on my website) if you want to discuss in private.
