### ISSUE TITLE
Create artwork for play icon on top of artwork

### ISSUE THREAD

**Issue by GianniCarlo** [GianniCarlo/Audiobook-Player#145]
Used for the cell of the currently playing book

Related: #139

**Comment by pichfl** [comment]
Some sketches for possible icons overlays or animations  ![d17e2921-6659-4b9d-80e0-b9fb41ee6da5](https://user-images.githubusercontent.com/194641/41202009-e53144ca-6cba-11e8-991f-fe47d1d73a40.jpeg)

I think a continuous animation like the one used in playlists in Apple‘s Music app could work quite well.

**Comment by GianniCarlo** [comment]
we might need to have a dark overlay underneath this new icon 🤔, on top of the default image for a playlist it can't be distinguished that well
