### ISSUE TITLE
Non-english title and chapter letter support

### ISSUE THREAD

**Issue by karb0f0s** [GianniCarlo/Audiobook-Player#15]
Hi! I am experiencing issues with books having non-english letters. App crashes if I upload file with non-us letters in it. If I rename it, app works well, but does not allow to see chapters and book title remains blank.

**Comment by GianniCarlo** [comment]
Hi @karb0f0s ! thanks for letting me know, can you help me with the name of the title so I can copy/paste and do local tests?

**Comment by GianniCarlo** [comment]
or better yet, do you mind sharing that file with me to my email gcarlo89@hotmail.com ? Thanks a bunch!

**Comment by karb0f0s** [comment]
Hi. I checked this in recent version and everything works just fine! Sorry for inconvenience. Previos versions really did suffer this trouble. Thanks for the great app.

**Comment by GianniCarlo** [comment]
👌 nice to know v1.3 is working fine. If you have any suggestions for future versions just let me know.
