### ISSUE TITLE
Audio not pausing when Apple Maps giving directions 

### ISSUE THREAD

**Issue by alexdnt33** [GianniCarlo/Audiobook-Player#151]
Apple Maps has a feature that allows apps that designate themselves as “spoken word audio” to be automatically paused when Maps is speaking directions in navigation. BookPlayer is not pausing when directions are being said in Maps, instead continuing to play in the background.

**Comment by GianniCarlo** [comment]
Thanks for your feedback @alexdnt33 , we'll be sure to test this out and see if we can include a fix for this for the upcoming major release at the end of the month 👍

**Comment by pichfl** [comment]
Very much in favor of this. I think I can tackle this when I’m back, I added a few handlers already and can continue from there.

**Comment by GianniCarlo** [comment]
#174 should fix this, tested with Google Maps, since Apple Maps doesn't let me try driving directions where I am now

**Comment by pichfl** [comment]
Can confirm, #174 fixes the interruptions for Apple Maps as well :)

**Comment by GianniCarlo** [comment]
@alexdnt33 we're currently doing a beta test of the new version, if you could provide us with your email, we could give you access

**Comment by alexdnt33** [comment]
@GianniCarlo Yeah, is there a way for me to privately send it to you?

**Comment by GianniCarlo** [comment]
@alexdnt33 you could send me an email to gcarlo89@hotmail.com

**Comment by GianniCarlo** [comment]
invitation sent!
