### ISSUE TITLE
Player does not resume playback in all cases

### ISSUE THREAD

**Issue by pichfl** [GianniCarlo/Audiobook-Player#155]
Check for proper handling of the `shouldResume` in notification. Likely related to #151 

- Setting a Timer in the Clock.app and having it gone off will pause but not unpause the player
- Same with playing and stopping a video in youtube: Player pauses but does not unpause
- Bringing up Siri has the same effect

I think the latter happens in other audio apps as well, but the former should not as the timer is merely an interruption and not a change in medium

**Comment by GianniCarlo** [comment]
In which specific cases has this happened? not sure what to test yet

**Comment by GianniCarlo** [comment]
#174 resolves all those points, except the youtube one, since that interruption isn't an 'unexpected' one, the app doesn't get the callback when the youtube video is paused

**Comment by pichfl** [comment]
Can confirm, #174 fixes the interruptions for Apple Maps as well :)
