### ISSUE TITLE
Jump to, or scroll to point in current track

### ISSUE THREAD

**Issue by nights62** [GianniCarlo/Audiobook-Player#17]
I have an audio book which is in two large tracks. I recently was listening to it and for some reason when I tried to rewind 30 seconds the player instead started the track over. I may be missing something so please correct me if I am wrong, but I was not able to find a way to jump back or drag the current point to late in the track. Since the file was 6+ hours long pressing the 30 second jump over and over was not an option. It would be nice to have a jump to specific time option or to be able to scroll through with your finger to a specific time in the track. 

Thanks 👍

**Comment by GianniCarlo** [comment]
Hey @nights62 , thanks for the feedback, this is most definitely in the pipeline. I recently finished a major refactor I had pending, so I can focus on this next 👌

**Comment by GianniCarlo** [comment]
solved by https://github.com/GianniCarlo/Audiobook-Player/commit/d6b4ca13a6c1527e1926cfeb4cf0057f0920ed3f I'm open to suggestions on how to improve it
