### ISSUE TITLE
Discussion: Update application data storage

### ISSUE THREAD

**Issue by bryanrezende** [GianniCarlo/Audiobook-Player#23]
What do you think about us updating the app to use [Realm.io](https://realm.io/) rather than UserDefaults to store user/book information? A coworker mentioned Realm as a good option for storing user data on-device and would open up a lot of possibilities for us, and seems to give us encryption built-in too. We could:

- Store Books as easily retrievable objects that include a list of files that comprise the book, playlist style. A lot of audiobooks are broken up like this, and playing broken-up audiobooks is a feature we should take a look at too!

- Book objects could hold all the information we need for them, rather than having individually labeled userDefaults based on the "dataWeWant_bookIdentifier" pattern. 

- Store individual book stats/store data we could eventually pull from other API's like Goodreads, instead of pulling that data repeatedly. 

- Store user listening stats and display them Audible style (or like Pocketcasts). I've always loved seeing these stats when I used audible, but I don't get them in any other audiobook app I've used.

I've never used Realm before but it seems pretty sweet! I just don't want to start looking into it without your input :)

**Comment by bryanrezende** [comment]
I'm going to look into tackling the storage/persistent data/history stuff in my fork and see how it works, and hopefully see if opens up new features for us. Made these issues, if you want to track them:

- Database Migration: bryanrezende/Audiobook-Player#3

Possible followup features:
- Multi-file Books: bryanrezende/Audiobook-Player#4
- Book Detail View: bryanrezende/Audiobook-Player#2

**Comment by GianniCarlo** [comment]
Hey @bryanrezende , sorry for the late response on this issue, the notification mail never popped up in my inbox.

Back in v1.0, I did consider Realm, but figured that it was a dependency that the project will not benefit that much from and UserDefaults was more than enought for the set of features that it currently had.

But most definitely I agree that we should move from UserDefaults once we start tackling these features, and I agree that Realm is a really good option, I have used it for all the projects in my current workplace and it hadn't let me down yet 👍

**Comment by pichfl** [comment]
As stated in other channels, I'm not sure we actually need this and I'm always a bit hesitant when it comes to commercial third party dependencies.

**Comment by GianniCarlo** [comment]
@pichfl we can try out Core Data

**Comment by pichfl** [comment]
I think this issue actually describes multiple problems and should probably be split into multiple issues in the future.

1. A better data store for book meta data (which is useful for many reasons)
2. A way to sync said store between user devices
3. Generate statistics

Realm could solve the first one in a very elegant way. The second one however pretty much describes [their paid business model,](https://realm.io/products/realm-platform/) which is impressive, but all things considered not interesting for a free app. 

Looking through https://github.com/vsouza/awesome-ios#database I found some things that look interesting but nothing was quite right. I also found [IceCream](https://github.com/caiyue1993/IceCream) which syncs Realm via CloudKit, which brings me to my final question.

Why don't we use just CloudKit? The free version scales with the active users and the private database counts against a users quota not the general quota (as discussed [here](https://forums.developer.apple.com/thread/35633)) and should be large enough to sync the little data we actually need to store very often.

**Comment by pichfl** [comment]
After some further discussion we came to the conclusion that CoreData will work fine for us. It provides good storage for the data we need to keep and comes without an extra dependency and there are ways to adopt iCloud and other sync solutions in the future.
