### ISSUE TITLE
Enable and test Swift compiler optimization for future Xcode versions

### ISSUE THREAD

**Issue by GianniCarlo** [GianniCarlo/Audiobook-Player#25]
For release 2.1 we had to disable the swift compiler optimization due to crashes in Release environment for release 2.0.

We hope this issue goes away with a new version of Xcode but it remains to be tested

**Comment by pichfl** [comment]
@GianniCarlo I did some testing regarding this but I'm not sure if I got the environment right, it seems to work for me in Xcode 9.3, you might want to check again.

**Comment by GianniCarlo** [comment]
Looks like it's fixed, I'll add a commit later updating to the "recommended" project settings
