### ISSUE TITLE
Headphone button control

### ISSUE THREAD

**Issue by 0507spc** [GianniCarlo/Audiobook-Player#27]
Not sure if it's just an issue with me, but clicking the headphone button does not pause the audio book. Like wise in car on Bluetooth I can't pause. 

https://stackoverflow.com/questions/15424578/how-can-we-handle-headphone-play-pause-button-events-in-foreground-in-ios

Seems to have the resolution. Will see if I can get a local version working, my swift knowledge is basic. Thanks for a great app!

**Comment by GianniCarlo** [comment]
Thanks for your feedback! and we'll be thrilled if you could help us adding this feature.

In the file `ListBooksViewController.swift` we already have the app listening for these events with `UIApplication.shared.beginReceivingRemoteControlEvents()` (inside `viewDidLoad`). We have a function placeholder for the events that just prints in the console the type of event received from the headphone button, we have a pending TODO there with a switch with all the possible cases.

I'm glad that you like the app, and would really appreciate your contribution

**Comment by GianniCarlo** [comment]
One thing to discuss here is what to do with a double tap, the app Overcast uses it I think to jump x secs. We could take the same approach

**Comment by bryanrezende** [comment]
Double tap could be chapter/file skip (with the single-tap skip seconds being something we can allow the user to set in the settings 15/30/60 seconds) - I've seen that feature requested for other apps, and it might be something we can add once we have multi-file books supported.

**Comment by GianniCarlo** [comment]
First implementation (https://github.com/GianniCarlo/Audiobook-Player/commit/d05b6bbfd36fc3bd5f256512b058cc6231c40b22) I kept it simple, seek forward/backward and next/previous track perform the same function respectively

This feature is open to improvements, for now I'll be closing this issue
