### ISSUE TITLE
How to set mp3 files info to enable Chapters button in player view?

### ISSUE THREAD

**Issue by aloveric** [GianniCarlo/Audiobook-Player#28]

**Comment by aloveric** [comment]
In iTunes, thanks~

**Comment by GianniCarlo** [comment]
Hi @aloveric I haven't seen a way in iTunes to mark chapters for mp3 files. Actually I haven't yet come across a mp3 file which has chapters. Usually m4a files have them, if you know more about the subject please let us know.

**Comment by GianniCarlo** [comment]
I've been searching around the web and found this https://auphonic.com/blog/2013/07/03/chapter-marks-and-enhanced-podcasts/ . They mention that the us a tool made in Python to process mp3 files and mark them

**Comment by GianniCarlo** [comment]
This is out of scope for this project so I'm closing this issue, feel free to continue the conversation though and I'll answer to the best of my ability 👌

**Comment by aloveric** [comment]
@GianniCarlo Thanks for your feedback. I will try your link to make chapter in mp3 or m4a files.

**Comment by aloveric** [comment]
I found an sample file https://auphonic.com/media/blog/auphonic_chapters_demo.mp3 that works in your player, cool~ And still work on how to add this.

**Comment by GianniCarlo** [comment]
Nice!, let us know how it goes 👍
