### ISSUE TITLE
On a small device, playback controls are difficult to use

### ISSUE THREAD

**Issue by kour1er** [GianniCarlo/Audiobook-Player#31]
On a small screen, when playing back an audiobook, the bottom controls (scrubber, speed, sleep and chapters) are very difficult to tap as they are all very close together and a little chopped off. I attach a picture to show what I mean.
![smallscreen](https://user-images.githubusercontent.com/34779600/34461883-bd2c4e08-ee2e-11e7-9bcd-5b01c6a62c4e.jpeg)

**Comment by GianniCarlo** [comment]
@kour1er thanks for the feedback, I'll take it into consideration for the next release this 2018 👌

**Comment by kour1er** [comment]
Do let me know if I can help testing with this issue. Happy to help

**Comment by kour1er** [comment]
Found another screen where the UI is a little odd on a smaller screen. (Settings)

![settings](https://user-images.githubusercontent.com/34779600/34499803-af93bf7e-efff-11e7-8dbe-f65706627245.jpg)

**Comment by GianniCarlo** [comment]
@kour1er sorry to get back to you after so long, but I pushed a commit that should make it better on smaller screens: https://github.com/GianniCarlo/Audiobook-Player/commit/124ebb97ed58547a5f5c2933e2c4203ca71134f7 I tried it on the simulator with the iPhone SE, let me know if it looks better on your device

**Comment by kour1er** [comment]
No worries - I don't have Xcode set up currently (traveling). Do you have a build on Testflight I could test?

**Comment by GianniCarlo** [comment]
@kour1er I'm setting it up 👍, I normally use Fabric for deployments, but it's been a few years since I tried Testflight, now is the perfect time check it out again.

To which email should I send the invitation?

**Comment by kour1er** [comment]
kour1er@icloud.com

**Comment by GianniCarlo** [comment]
@kour1er invitation sent 👍, that build only has the UI improvements, it doesn't have the support for remote events that I later added

**Comment by kour1er** [comment]
Testflight worked great.

The settings screen is perfect now.

The playback screen still has a minor overlap issue between the sleep and current chapter display. I attach a screenshot

![controls](https://user-images.githubusercontent.com/34779600/35589443-c5293726-05fb-11e8-8c48-31ee541a5e2f.jpg)

**Comment by GianniCarlo** [comment]
waiting for Apple's review in Testflight of the new build that will surely solve that, Thanks @kour1er for helping with the testing 👍

**Comment by kour1er** [comment]
Just tested and the layout is now great on small devices, nice 👌🏻

**Comment by GianniCarlo** [comment]
great! thanks for helping out @kour1er . I'll send a new version to the appstore later today or tomorrow morning
