### ISSUE TITLE
Starts playing when disconnect Bluetooth

### ISSUE THREAD

**Issue by sebphillips** [GianniCarlo/Audiobook-Player#32]
I listen to books in my car which connects via Bluetooth, when I turn off my car, the Bluetooth disconnects and a couple seconds later the book starts playing out loud. Minor annoyance but overall this is the best book player on the market, would also love a web upload interface!

iPhone X 11.2.5

**Comment by GianniCarlo** [comment]
@sebphillips thanks for your feedback! I'm glad you like it. We'll be sure to fix this issue for the next release
