### ISSUE TITLE
 Hide rating

### ISSUE THREAD

**Issue by AndreyDovzhenko** [GianniCarlo/Audiobook-Player#33]
How to remove the appearance of the rating after the production of auido?

**Comment by DanielDeSua** [comment]
The PlayerViewController has a function @objc func bookEnd (),  in it you need to comment out this call to the function @objc func requestReview () - It through the notification and calls this window 

 @objc func bookEnd() {
    self.playButton.setImage(self.playImage, for: UIControlState())
//    self.requestReview()
  }

**Comment by GianniCarlo** [comment]
@DanielDeSua thanks for responding, I'll add a compiler flag to disable that line for debug mode. Leaving this issue open for that reason

**Comment by GianniCarlo** [comment]
Flag added, if you have your scheme build configuration set to `Debug`, the popup shouldn't appear
