### ISSUE TITLE
Folders

### ISSUE THREAD

**Issue by Brainslugger** [GianniCarlo/Audiobook-Player#35]
It would be nice to have folders to put the books into.

**Comment by GianniCarlo** [comment]
@Brainslugger I'll have to think a way to make it work alongside the playlist feature that's going to be included later 🤔, thanks for your feedback 👍

**Comment by pichfl** [comment]
After recent discussion @GianniCarlo and I decided to not support folders in foreseeable future. The reasoning behind it was as follows:

- Playlists (which will come in the next major version) allow for many of the use cases such as grouping parts of books and changing order
- The overlap between folders and playlists means we have to teach users two new functions with similar but different behaviors
- Folders provide expectations such as options for nesting and management which can become complicated very fast. Getting all the interactions right is hard and even big apps and their UIs struggle here
- Most users won't likely have enough books on their device to require more structure

While I'm closing this ticket to maintain focus in the project, we'll keep the idea in mind and we'll reopen this when necessary.
