### ISSUE TITLE
Add a setting for "Autoplay" that will play the next audiobook in the list

### ISSUE THREAD

**Issue by e7mac** [GianniCarlo/Audiobook-Player#37]
This is a feature that I keep customizing for myself and wanted to see if there was wider interest before I clean up the code and make a PR. It is not perfect, but helps me use the app without the need for #14 and #8.

**Comment by GianniCarlo** [comment]
Sounds great! I would like to include it in the next minor release 2.2 which will include search functionality too. Thanks for your contributions @e7mac !
