### ISSUE TITLE
UI/UX redesign

### ISSUE THREAD

**Issue by pichfl** [GianniCarlo/Audiobook-Player#38]
Hi. I was really happy to find this project and app as it solves exactly the problem I always had and does it in a great way. 

Since I haven't done iOS development in quite some time and I'm looking for a new side project I was wondering if you would be interested in a more wholesome UI concept custom made for the app. 

If so, I'll spend some time redesigning all screens in the app. If you like the result, I will also prepare all necessary assets from those redesigns and try to implement the changes in a PR. 

Is this something you would be interested in?

**Comment by GianniCarlo** [comment]
Hi @pichfl, yes please!, it would be great to see how you envision this app. I'm no designer myself, so I'm aware that the app could be and look so much better. Let me know how I can help you.

**Comment by pichfl** [comment]
Wonderful! Since I can use Xcode and I do understand Swift, for now all you need to do is to be patient until I have time to flesh out the first designs 🙂 

If you want you can also post links to apps or designs you enjoy in particular that I can use as a general source for mood and inspiration.

**Comment by pichfl** [comment]
A first draft a little closer to the Books and Music app. I really like the interaction of the iBooks app with the cover, so in these mockups the cover can be dragged left or right to skip or rewind by a specified amount. Tapping the cover will play / pause. This leaves a lot of open space so the design works even on the iPhone SE. I went with darker colors for the Player view considering the fact many including myself will use this app at night. The colors of the play screen are taken algorithmically from the cover images (I have a reference implementation for this in JS so porting it to swift should be possible).

The library and settings screens take cues from many of the native apps.

I know this takes a few of the more custom view interactions out of the app, but it was something I was willing to try. Mostly to support all phone variations and dark cards on a dark background can be difficult to discern. 

Also missing are most icons as I was sitting on the couch creating these mockups and drawing with the trackpad only is not my forte, I'll add them back in later iterations. 

![1 library](https://user-images.githubusercontent.com/194641/37548697-fd1444a4-2979-11e8-81a0-10367535b5a2.png)
![2 player](https://user-images.githubusercontent.com/194641/37548694-fcddca0a-2979-11e8-9e17-0eb7528adbc8.png)
![2 player two](https://user-images.githubusercontent.com/194641/37548696-fcf978f4-2979-11e8-9515-e43e0a5e95e3.png)
![3 settings](https://user-images.githubusercontent.com/194641/37548693-fcc46344-2979-11e8-86a2-7837eca47fc3.png)

**Comment by GianniCarlo** [comment]
I'll leave a block of comments per each screen

**Comment by GianniCarlo** [comment]
Screen: List of books
It looks much cleaner 👍, two things though,
1.- I assume that the first row has the title in black because that's the one that is playing? If that's the case, I would argue that it's not too noticeable for the user that has a large list. I don't think it's that big of a deal because once it's in the device, we can try different things regarding that.
2.- I like the new design of the bottom bar, I was about to argue about putting some kind of play/pause in there so the user doesn't have to open up the player view to play/pause the book. But actually, I usually just do it from the lock screen. What do you think?

Another thing, as I mentioned via iMessage, it'd be great if you could consider how the UX for the playlist creation/listing would be

**Comment by GianniCarlo** [comment]
Screen: Player
1.- I'm not closed to the idea of `pushing` the player in a navigation controller, although most players I've encountered usually `present` them and lets you minimize it so you can still go about the app and drag it upwards if need be to present the player too. This interaction of dragging to `present` would be replaced by tapping to `push` the player. I'd like to hear your thoughts on this point.

2.- The play/pause button are a little hard to distinguish as they are right now
3.- I don't know how intuitive would be the new way of skipping time, specially for the existing users 🤔, we might need to have some cues, or some way to let them know the new way.

I do like that it looks more organized now

**Comment by GianniCarlo** [comment]
Screen: Settings
I agree that going for the native look is always a safe bet 👍

**Comment by GianniCarlo** [comment]
Really great work @pichfl , I don't know how manageable reviewing screens in github would be in the long run, so if you got a tool better suited for this let me know

**Comment by pichfl** [comment]
Regarding reviews: While a little less public, I use https://www.goabstract.com to manage my design files, I'll invite you later.

#### Library

1. Only finished books are grayed out. The playing book is missing an indicator icon.
2. The bottom bar is based on the same element that can be found in the relaunched App Store in iOS 11. Tapping it would bring you back to the player. Adding a Pause/Play action on the right side should be no problem. I'd even suggest to have this floating element on all screens of the app with the player being the obvious exception.
3. I'll consider playlists in the next iteration, this needs some research as I'm not very fond of the Playlist features in most popular apps like Apple Music and Spotify.

#### Player

1. I went for push mostly because the iPhone X reserves drag/swipe from the bottom for OS gestures and the App Store app uses a `push` on its bottom banners. Using a `present` segue for the player screen is perfectly fine, I'll just replace the chevron in the upper left with one that points downwards and remove the right arrow from the library cells. 
2. Yes and I'm not sure I'll be leaving them there, I'll have to rethink the playback controls anyway.
3. The idea was to make the cover follow the push segue with a little delay, partially showing the controls behind the cover. It should also work when presenting the player instead.
4. I think there is plenty of space that we can show the controls, even on a small phone, so I'll bring them back in the next iteration. 

Thanks a lot for taking the time for this.

**Comment by pichfl** [comment]
Further design iterations will be made public with Invision: https://invis.io/P9GE3A2F67D#/285682534_Player

**Comment by pichfl** [comment]
Closed in favor of the issues describing the work required in each scene
