### ISSUE TITLE
Adjustable skip-forward/backward duration

### ISSUE THREAD

**Issue by quinncomendant** [GianniCarlo/Audiobook-Player#42]
The current skip-forward/backward time of 30 seconds is not right for me. Can we have the option to customize these values? E.g., I would use 10s backward and 60s forward.

**Comment by GianniCarlo** [comment]
Thanks for the feedback! while I had considered adding the ability to change the value for the time skip, I hadn't thought about having different time values for skipping forward and backward and it really makes sense 🤔 I'll try to add it for the next minor release at the end of march 👍

**Comment by pichfl** [comment]
@quinncomendant good news! While this didn't make it into the latest release, the new player UI in #44 & #75 is preparing for this and it will most likely be included into the upcoming major release 🙂
