### ISSUE TITLE
Extend existing guards in PlayerViewController

### ISSUE THREAD

**Issue by pichfl** [GianniCarlo/Audiobook-Player#49]
Instead of adding a separate `if`, pull the query into the guard.

https://github.com/GianniCarlo/Audiobook-Player/blob/44ddec4c9359984acd7d66c568dc1190213ef037/Audiobook%20Player/PlayerViewController.swift#L217-L230

https://github.com/GianniCarlo/Audiobook-Player/blob/44ddec4c9359984acd7d66c568dc1190213ef037/Audiobook%20Player/PlayerViewController.swift#L232-L258

**Comment by pichfl** [comment]
After talking to a colleague of mine I think we should keep this as is.

**Comment by GianniCarlo** [comment]
I would argue the opposite in those specific cases, for the following reason: there's nothing happening after the `if let` statement, so if we already have a guard in place, I would rather do all the unwrapping there and then thave the other statements without any identantion. This idea is grabbed from the 'golden path' which states that we should check first for all the error states, so we can always have the success state at the end

**Comment by pichfl** [comment]
You're right. I think I misunderstood mostly because of the `PlayerManager.sharedInstance.stop()` in the second block, which does not have to be there but come further down as well.

**Comment by GianniCarlo** [comment]
closed with #50
