### ISSUE TITLE
Quick Play/Pause button not working

### ISSUE THREAD

**Issue by Daniel-Katz** [GianniCarlo/Audiobook-Player#58]
Yesterday, the quick play or pause button worked just fine. Now, the button doesn't work.
I tried it with apple music and ibooks, and the quick play button on my headset works.
Something else I figured out is that the quick play from the apple device itself (when dragging upwards) has the PLAY button grayed out. The forward/rewind 30 secs buttons are both fine, just if I want to play or pause, I have to open the app itself.
Please help.

**Comment by GianniCarlo** [comment]
Thanks for the report @Daniel-Katz I'll push a fix asap to the appstore

**Comment by Daniel-Katz** [comment]
awesome, thanks

**Comment by GianniCarlo** [comment]
@Daniel-Katz can you attach please a screenshot of the button grayed out?

**Comment by GianniCarlo** [comment]
I'll attach some screenshots, maybe I'm not understanding which play button is not working, it'll be great if you could help with a more detailed description to debug this:
![img_0609](https://user-images.githubusercontent.com/14112819/38216846-bf3e003c-3691-11e8-902b-61f37fcdfc81.PNG)
![img_0610](https://user-images.githubusercontent.com/14112819/38216847-bf576806-3691-11e8-825a-a9aa5d0457e9.PNG)
![img_0611](https://user-images.githubusercontent.com/14112819/38216856-c2b166d2-3691-11e8-9f54-05a94b47eda0.PNG)
![img_0612](https://user-images.githubusercontent.com/14112819/38216857-c2d3a3f0-3691-11e8-963a-f7c4dcdfc48b.PNG)
![img_0614](https://user-images.githubusercontent.com/14112819/38216858-c2fb0d8c-3691-11e8-81cb-7ce46d8ed250.PNG)
![img_0615](https://user-images.githubusercontent.com/14112819/38216859-c317b4b4-3691-11e8-98a2-d4bc547869f3.PNG)

**Comment by Daniel-Katz** [comment]
![img_3043](https://user-images.githubusercontent.com/6530218/38222132-1c9e5550-36b1-11e8-9d1a-8238b0919655.PNG)

**Comment by Daniel-Katz** [comment]
![img_3044](https://user-images.githubusercontent.com/6530218/38222193-582a045c-36b1-11e8-8d7e-cb47d974b9f0.PNG)

**Comment by GianniCarlo** [comment]
this commit might have caused this: https://github.com/GianniCarlo/Audiobook-Player/commit/0e1abb6420e4135819e42a8e4c74ec3532048e56 I'll revert part of it and release 2.2.1 which should fix it

**Comment by Daniel-Katz** [comment]
thanks. Should I update the app?

**Comment by GianniCarlo** [comment]
@Daniel-Katz probably tomorrow 2.2.1 will be up in the appstore, you're welcome to run the project in your iphone and see if that works. I'm keeping open this issue until 2.2.1 is out and to check if it fixed your problem

**Comment by Daniel-Katz** [comment]
I'll post one I know. Thanks again

**Comment by Daniel-Katz** [comment]
I updated, and it works. Thanks!

Before I go, if I might make a suggestion to please add a "Contact Us" button somewhere in the app (maybe in the settings icon?), even if it only directs them to this github account.
I only coincidentally found this account, so I was pretty certain I would have to find another app to use, which would have been a shame, since I LIKE this app.

**Comment by GianniCarlo** [comment]
@Daniel-Katz glad it works 👌. Great suggestion, I'll open up a new issue with that 👍
