### ISSUE TITLE
Uploading via WiFi

### ISSUE THREAD

**Issue by bwdowikowski** [GianniCarlo/Audiobook-Player#6]
Hi @GianniCarlo,
what do you think about "Sharing via WiFi" like in VLC? Is it worth implementing to?

**Comment by GianniCarlo** [comment]
Hi @Dudi00 ! it's definitely an useful feature, I've used it many times in other apps too. This weekend I'm aiming to have an interface for all the upcoming import options #7 so on the weekend after it we can include each module neatly. That being said, PR are always welcomed 😁

**Comment by Dudi00** [comment]
Cool I always wanted to have that kind of audiobook player with this feature. Can't wait for an interface :)

**Comment by GianniCarlo** [comment]
Leaving [this](https://github.com/httpswift/swifter) as a reference for later

**Comment by GianniCarlo** [comment]
Definitely solved by #12
