### ISSUE TITLE
When using command line to merge audio files, the length of the audiobook doesn't extend

### ISSUE THREAD

**Issue by Daniel-Katz** [GianniCarlo/Audiobook-Player#65]
Often enough, an audiobook is split up into several smaller files, which can get annoying when using this app since (as far as I'm currently aware) it doesn't allow for having multiple files play one after the other (iBooks does this when they have the same album) and I was able to find a way around the annoyance by merging the many files via Windows command line:

      copy /b file1.mp3+file2.mp3+file3.mp3 outputfile.mp3
      (let's say for example files 1,2,3 are 5 mins long each, the result should be 15 minutes long)

The problem is that while **_outputfile.mp3_** worked fine when I tried to play it via VLC, when I uploaded it to the app, the duration of the audiobook was only as long as the first file (with the rest of it apparently being inaccessible), leaving me with apparently a much larger file that only counted as the first file, unless I used VLC (I tried Google Drive and it had the same issue).

A way I found to fix the issue (a bit annoying but I made it work) was to use ConverterLite to convert my **_outputfile.mp3_** into an mp3 (sounds redundant, I know), which apparently wiped whatever data was telling the app that it was only as long as the first file (in the case of the example, the app thought **_outputfile.mp3_** was only 5 mins long), which was a little frustrating, since I searched the file's properties and I was unable to find anything saying that the **_outputfile.mp3_** was shorter than it was.

Anything you can do for this?

**Comment by pichfl** [comment]
Hi @Daniel-Katz I have three answers for you. 

First, have a look at our brand new [Wiki][https://github.com/GianniCarlo/Audiobook-Player/wiki] which includes a few tools to create M4B based files which are the common standard for combining MP3 files into and audiobook.

Second, we are planning support for playlists for the next big release of the app. Those will allow you to sort your files and will automatically play each file in them. 

Third, we just released version 2.2.1 which brings a new option in the Settings menu available from the main screen which allows you to autoplay all files one after the other in your library. That way you only have to take care of the IDE3 tags inside the files and filenames which we use for sorting.

Having said that, I'll also have to inform you that merging a binary format with `copy` on Windows will not have the desired effect you seek as MP3 files rely on header information at the beginning of each file, which would end up in the middle of your merged file. To properly merge MP3 files you will need a different tool, but I'd recommend merging them with one of the apps I mentioned as they are able to use the existing files as chapters in your combined audiobook.

I'm closing this ticket as it does not describe a problem with the app and we are trying to keep focus on app issues and enhancements. 🙂
