### ISSUE TITLE
TextView in AudioBook lists Scene is editable

### ISSUE THREAD

**Issue by maxfremars** [GianniCarlo/Audiobook-Player#72]
Users can edit and delete the text view in the audio book lists scene. 

Effect should be the same in master and next/major branch.

![img_5244](https://user-images.githubusercontent.com/3366634/39418791-9a5ff6f4-4c5c-11e8-8f41-3cd9cc85660b.png)
![bildschirmfoto 2018-04-30 um 09 52 29](https://user-images.githubusercontent.com/3366634/39418752-7f8eda0c-4c5c-11e8-8363-0d88941d92c2.png)

**Comment by pichfl** [comment]
Good call and thank you for reporting this. As it is not a critical bug, I'd postpone fixing this for now since this view will most likely be removed in the next release anyway.
