### ISSUE TITLE
New Empty State for Library and Playlists

### ISSUE THREAD

**Issue by pichfl** [GianniCarlo/Audiobook-Player#73]
Both the new Library screen and a freshly created Playlist need a good looking and helpful placeholder that shows up when no book was added yet.

This replaces #72 and extends on #46 

I'll add mockups as soon as possible.

**Comment by pichfl** [comment]
I added artwork and views for both, only the "Add" cell is missing. Is there a way to reuse the UITableCell or is it not worth the effort?

**Comment by GianniCarlo** [comment]
Since it's registered in the BaseListVC it shouldn't be a major problem. Just to be clear, in the library, when it's empty, the "Add" cell will be visible alongside the default artwork on the back right?

**Comment by pichfl** [comment]
Here are two mockups for the screens. The "Add" button is centered in both. I'm not yet sure about the text for the Playlist button, but I think file is more appropriate in that context. 

### Empty Library

![library](https://user-images.githubusercontent.com/194641/40303276-7109f6aa-5cf2-11e8-82a6-41c9ed46fede.png)

### Empty Playlist 
![library empty](https://user-images.githubusercontent.com/194641/40303266-68011d2c-5cf2-11e8-9de3-4bccaccd7c86.png)
