### ISSUE TITLE
Merge multiple files in to one as preupload process

### ISSUE THREAD

**Issue by icanswiftabit** [GianniCarlo/Audiobook-Player#8]
This is related to #6 , sometimes audiobooks are splited into several smaller files. So why this app would not join them in to one large and then upload.

**Comment by GianniCarlo** [comment]
Agreed, this would be a nice feature to have. Though not as pressing as the other features, it sure is something to take into account once we have the other functionality 👍

**Comment by GianniCarlo** [comment]
Reference:
- http://stackoverflow.com/questions/7656512/combining-two-caf-files-on-iphone?noredirect=1&lq=1
- http://stackoverflow.com/questions/11596945/how-to-merge-two-mp3-files-ios

Once I'm finished with local apps integration, I'll tackle this issue

**Comment by GianniCarlo** [comment]
I think the best approach would be to let users create playlists. This makes sense to have as a feature and I think it would partially cover the need of users to merge files into one

**Comment by pichfl** [comment]
There are many good (and/or free) tools available for this task on macOS, Windows and even Linux. 

I'm closing this down in favor of #14 which provides a similar result and will serve more users while keeping the app focussed on playing audio books. 🙂

If someone is up for the task and wants to create a companion app for BookPlayer, we would happily promote it.
